name: "ll_project" # (1)
type: "python:3.10"


relationships: # (2)
    database: "db:postgresql"


# 웹에 배포할 때 사용할 설정
web: # (3)
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application" # (4)
    locations: # (5)
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true


# 애플리케이션에 필요한 디스크 크기 (MB 단위)
disk: 512 # (6)

# 로컬 읽기/쓰기를 기록합니다
mounts: # (1)
    "logs":
        source: local
        source_path: logs


# 애플리케이션 실행 중에 다양한 지점에서 실행되는 훅
hooks: # (2)
    build: |
        pip install --upgrade pip # (3)
        pip install -r requirements.txt
        pip install -r requirements_remote.txt


        mkdir logs
        python manage.py collectstatic # (4)
        rm -rf logs
    deploy: | # (5)
        python manage.py migrate
